name: moneymatter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.1
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  http: ^1.2.1
  oktoast: ^3.4.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  intl: ^0.19.0
  dio: ^5.4.3+1
  flutter_inappwebview: ^6.0.0
  syncfusion_flutter_charts: ^25.2.5
  carousel_slider: ^4.2.1
  flutter_slidable: ^3.1.0
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
